### PR TITLE
Update intros.md meenu

### PR DESCRIPTION
**Pull request by Meenu-Bhati**

### CODE REVIEW

**Review by RayStick — APPROVED** [review]
Look good - you can merge now! (I hope)

**Comment by Meenu-Bhati** [comment]
Thank you

**Comment by Meenu-Bhati** [comment]
This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by RayStick** [comment]
Okay, thanks for letting me know. We will work on the access and get back to you. 
For now, I will press 'Merge'

**Comment by RayStick** [comment]
@Meenu-Bhati - know I have pressed 'merge' you should see that your name had been added to the [intros.md file in the main branch](https://github.com/aim-rsf/training/blob/main/github-intro/intros.md). Does that make sense?

**Pull request merged**
