### PR TITLE
Add Helen into Intro.md

### PR DESCRIPTION
**Pull request by RayStick**
Add Helen's name to the Intros.md file, as per the workshop instructions

### CODE REVIEW

**Comment by RayStick** [comment]
Hi Helen! @thisisyingzi 

Sorry I missed a message from you in the ZOOM chat yesterday until right at the end of the meeting!
I see you have successfully created a branch without forking and put your name in the correct place 🎉 

I went ahead and pressed 'Create Pull Request' for you, to get this reviewed and merged. 

Screenshot 2022-10-19 at 08 28 05

@eirini-zormpa I have put you down as a reviewer - because I created the PR, I cannot review it (logical).

**Comment by thisisyingzi** [comment]
Morning Rachael thank you very much! Glad to know i did it right yesterday-a bit lost in later stage😅 

BTW May I ask is it possible for me to sign up for the upcoming R programming workshop? I remembered Eirini mentioned it is originally for internal colleagues of Tiring institute? 

Many thanks again and have a nice day!

Kind regards, 
Helen

**Comment by RayStick** [comment]
Hi Helen, you definitely did it right 🎉 
We'll make sure to get back to you about the other workshops via email. Thanks for taking part!

**Review by eirini-zormpa — APPROVED** [review]
Looks great :rocket:

**Comment by eirini-zormpa** [comment]
woop woop, you can merge in your pull request now @thisisyingzi ✨

**Pull request merged**
